spring.application.name=AI Hotel Search Assistant
# =========================================
# SERVER
# =========================================
server.port=8080


# =========================================
# DATABASE CONFIGURATION (NEON POSTGRES)
# =========================================
spring.datasource.url=jdbc:postgresql://ep-bold-queen-aq10is92-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always


# =========================================
# JDBC SETTINGS
# =========================================
spring.datasource.hikari.maximum-pool-size=5


# =========================================
# SPRING AI + GROQ
# =========================================
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai

# GROQ MODEL
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile

# Optional
spring.ai.openai.chat.options.temperature=0.2


# =========================================
# LOGGING
# =========================================
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.springframework.jdbc.datasource.init=DEBUG
logging.level.org.springframework.ai=DEBUG
logging.level.com.tatajavvadi.ai_hotel_search=DEBUG
